spring:
  http:
    encoding:
      force: true
      charset: UTF-8
    thymeleaf:
      cache: false
      check-template-location: true
      content-type: text/html; charset=utf-8
      enabled: true
      encoding: UTF-8
      prefix: classpath:/templates/
      suffix: .html
      mode: LEGACYHTML5
com:
  staff0: ${server.port}
